### ISSUE TITLE
Add Friends

### ISSUE THREAD

**Issue by mustafacagataytulun** [mustafacagataytulun/bounswe574-2022#15]
As a user, I want to add other colearners as friends, so that I can see them on a list to communicate quickly.

**Comment by gulsahmkapucu** [comment]
Adding friend functionality is completed, I'm working on the notifications functionality.

**Comment by gulsahmkapucu** [comment]
This feature is completed with some extra functionality like getting friend's notifications who makes contributions to the related spaces.
