### ISSUE TITLE
Beginning development of frontend of text annotation

### ISSUE THREAD

**Issue by bpostalci** [mustafacagataytulun/bounswe574-2022#22]
With this feature, users will be able to add annotations on an article of a Colearning space.

**Comment by bpostalci** [comment]
* The system shall only enable users to annotate "content" text. (To avoid selecting text of other elements like <h1>, <button> etc.)

**Comment by bpostalci** [comment]
* Users shall be able to add annotations on Learning Spaces' articles

**Comment by bpostalci** [comment]
* Use [text quote selector](https://www.w3.org/TR/annotation-model/#text-quote-selector) to store annotations

**Comment by mustafacagataytulun** [comment]
Initial development and deployment of annotation service have been completed. I created a page on [Wiki](https://github.com/mustafacagataytulun/bounswe574-2022/wiki/Annotation-Service) to document how it can be used.

**Comment by bpostalci** [comment]
* Send creator of the annotation to annotation service
